version: '3.8'
services:
  payme-database:
    image: postgres:14-alpine
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - '${DB_HOST_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
  
    