version: '3.8'
services:
  payme-database:
    image: postgres:14-alpine
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - '${DB_HOST_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
  api:
    container_name: payme-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_HOST_PORT=$DB_HOST_PORT
      - DB_DIALECT=$DB_DIALECT
      - AUTH_SECRET=$AUTH_SECRET
      - DB_URL=$DB_URL
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - payme-database
volumes:
  database:
    driver: local
  
    